---
- name: Deploy Dev Test environment on Azure
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    az_environment: dev

  tasks:

    - name: Deploy Database Instance
      include_role:
        name: nehrman.azure


    - name: Deploy Web Apps Instance
      include_role:
        name: nehrman.azure
